"""Regenerate src/scripts.rs from poe's own completion-script generators.

poe's scripts are kept verbatim except for the two per-Tab data calls, which are swapped
for `devkit complete tasks` / `devkit complete args`. Run from anywhere with the repo's
venv active (it needs `poe` on PATH); re-run when poethepoet's generator changes:

    uv run python crates/aeth-devkit-complete/gen_scripts.py
"""
import subprocess
from pathlib import Path

HERE = Path(__file__).parent
OUT = HERE / "src" / "scripts.rs"


def poe(*args: str) -> str:
    # Decode as UTF-8 explicitly: a console redirect on Windows would otherwise hand back
    # cp1252 and mangle the em dashes in poe's comments.
    return subprocess.run(["poe", *args], check=True, capture_output=True, encoding="utf-8").stdout.replace("\r\n", "\n")


ps = poe("_powershell_completion")
bash = poe("_bash_completion")

PS_SUBS = [
    ("& poe _describe_task_args $TaskName $TargetPath 2>$null", "& devkit complete args $TaskName $TargetPath 2>$null"),
    ("& poe _describe_task_args $TaskName 2>$null", "& devkit complete args $TaskName 2>$null"),
    ("& poe _list_tasks $TargetPath 2>$null", "& devkit complete tasks $TargetPath 2>$null"),
    ("& poe _list_tasks 2>$null", "& devkit complete tasks 2>$null"),
    ("# Generated by poethepoet\n", "# Generated by poethepoet, adapted by aeth-devkit: task data comes from `devkit complete`\n"),
    ("#   poe _powershell_completion | Out-String | Invoke-Expression", "#   devkit complete script --powershell | Out-String | Invoke-Expression"),
]
BASH_SUBS = [
    ('tasks=$(poe _list_tasks "$target_path" 2>/dev/null)', 'tasks=$(devkit complete tasks "$target_path" 2>/dev/null)'),
    (
        'task_args_data=$(poe _describe_task_args         "$current_task" "$target_path" 2>/dev/null)',
        'task_args_data=$(devkit complete args "$current_task" "$target_path" 2>/dev/null)',
    ),
    ("# Generated by poethepoet\n", "# Generated by poethepoet, adapted by aeth-devkit: task data comes from `devkit complete`\n"),
]

for old, new in PS_SUBS:
    assert ps.count(old) == 1, ("powershell", old, ps.count(old))
    ps = ps.replace(old, new)
for old, new in BASH_SUBS:
    assert bash.count(old) == 1, ("bash", old, bash.count(old))
    bash = bash.replace(old, new)

for text in (ps, bash):
    assert "poe _list_tasks" not in text and "poe _describe_task_args" not in text
    assert '"##' not in text, "raw-string delimiter collision"

OUT.write_text(
    "//! Shell completion scripts: poe's own generated scripts with the two per-Tab data calls\n"
    "//! (`poe _list_tasks`, `poe _describe_task_args`) swapped for `devkit complete tasks` /\n"
    "//! `devkit complete args`. Everything else — global option lists, `-C` handling, `--`\n"
    "//! pass-through, choice completion — is poe's, verbatim, so behaviour is identical and only\n"
    "//! the data source is faster.\n"
    "//!\n"
    "//! Generated by `gen_scripts.py` next to this crate's Cargo.toml; do not edit by hand.\n"
    "\n"
    "/// `devkit complete script --powershell`; add to `$PROFILE` via `| Out-String | Invoke-Expression`.\n"
    'pub const POWERSHELL: &str = r##"' + ps + '"##;\n'
    "\n"
    "/// `devkit complete script --bash`; `source <(devkit complete script --bash)` from `.bashrc`.\n"
    'pub const BASH: &str = r##"' + bash + '"##;\n',
    encoding="utf-8",
    newline="\n",
)
print(f"wrote {OUT}")
