use std::path::PathBuf;

use aeth_devkit_complete::install::{
  FileAction, POWERSHELL_LINE, bash_file_action, install_bash, install_powershell, patch_profile, powershell_profile,
  powershell_shim_path,
};
use aeth_devkit_core::process::RecordingRunner;

// ---- PowerShell profile text ---------------------------------------------------------------

#[test]
fn missing_profile_becomes_just_the_devkit_line() {
  let (text, log) = patch_profile(None);
  assert_eq!(text, format!("{POWERSHELL_LINE}\n"));
  assert!(!log.is_empty());
}

#[test]
fn poes_line_is_replaced_and_other_lines_survive() {
  let original = "Set-Alias ll Get-ChildItem\npoe _powershell_completion | out-string | invoke-expression\nfunction x { }\n";
  let (text, log) = patch_profile(Some(original));
  assert_eq!(text, format!("Set-Alias ll Get-ChildItem\nfunction x {{ }}\n{POWERSHELL_LINE}\n"));
  assert!(log.iter().any(|l| l.contains("poe _powershell_completion")), "{log:?}");
  assert!(log.iter().any(|l| l.contains("added")), "{log:?}");
}

#[test]
fn profile_patch_is_idempotent_and_case_insensitive() {
  let (once, _) = patch_profile(Some("x\n"));
  let (twice, log) = patch_profile(Some(&once));
  assert_eq!(once, twice);
  assert!(log.is_empty(), "{log:?}");
  // A hand-typed variant with different casing still counts as present.
  let lower = format!("x\n{}\n", POWERSHELL_LINE.to_lowercase());
  let (text, log) = patch_profile(Some(&lower));
  assert_eq!(text, lower);
  assert!(log.is_empty(), "{log:?}");
}

#[test]
fn profile_patch_preserves_crlf_and_a_missing_trailing_newline() {
  let (text, _) = patch_profile(Some("a\r\npoe _powershell_completion | Out-String | Invoke-Expression\r\nb"));
  assert_eq!(text, format!("a\r\nb\r\n{POWERSHELL_LINE}\r\n"));
}

// ---- bash file decision --------------------------------------------------------------------

const SCRIPT: &str = "# Bash completion for poe\n# Generated by poethepoet, adapted by aeth-devkit: task data comes from `devkit complete`\ncomplete -F _poe_complete poe\n";

#[test]
fn bash_file_decisions() {
  assert_eq!(bash_file_action(None, SCRIPT), FileAction::Write);
  assert_eq!(bash_file_action(Some(SCRIPT), SCRIPT), FileAction::Unchanged);
  // poe's own generated file (what `poe _bash_completion > …/poe` leaves behind) is ours to replace.
  assert_eq!(
    bash_file_action(
      Some("# Bash completion for poe\n# Generated by poethepoet\n_poe_complete() { }\n"),
      SCRIPT
    ),
    FileAction::Write
  );
  // An older devkit-generated file too.
  assert_eq!(bash_file_action(Some("# adapted by aeth-devkit\nold\n"), SCRIPT), FileAction::Write);
  // Anything else is the user's.
  assert_eq!(
    bash_file_action(Some("# my own poe completion\ncomplete -W 'a b' poe\n"), SCRIPT),
    FileAction::RefuseForeign
  );
}

// ---- PATH check ----------------------------------------------------------------------------

// ---- $PROFILE lookup -----------------------------------------------------------------------

#[test]
fn powershell_profile_asks_powershell_and_trims() {
  let r = RecordingRunner::new(0);
  r.script(
    "powershell",
    &["-NoProfile"],
    0,
    "C:\\Users\\me\\Documents\\WindowsPowerShell\\Microsoft.PowerShell_profile.ps1\r\n",
  );
  assert_eq!(
    powershell_profile(&r).unwrap(),
    PathBuf::from("C:\\Users\\me\\Documents\\WindowsPowerShell\\Microsoft.PowerShell_profile.ps1")
  );
  let failing = RecordingRunner::new(1);
  assert!(powershell_profile(&failing).is_err());
}

// ---- file-level installs -------------------------------------------------------------------

#[test]
fn install_powershell_writes_both_artifacts_and_is_idempotent() {
  let dir = tempfile::tempdir().unwrap();
  let profile = dir.path().join("WindowsPowerShell").join("profile.ps1");
  let shim = powershell_shim_path(dir.path());
  let log = install_powershell(&profile, &shim, "# shim\n", false).unwrap();
  assert!(!log.is_empty());
  // The profile gets one line; the script itself lives in its own file.
  assert_eq!(std::fs::read_to_string(&profile).unwrap(), format!("{POWERSHELL_LINE}\n"));
  assert_eq!(std::fs::read_to_string(&shim).unwrap(), "# shim\n");
  assert!(
    install_powershell(&profile, &shim, "# shim\n", false).unwrap().is_empty(),
    "second run must be a no-op"
  );
}

#[test]
fn install_powershell_refreshes_a_stale_shim_without_rewriting_a_current_profile() {
  let dir = tempfile::tempdir().unwrap();
  let profile = dir.path().join("profile.ps1");
  let shim = powershell_shim_path(dir.path());
  install_powershell(&profile, &shim, "# old\n", false).unwrap();
  let log = install_powershell(&profile, &shim, "# new\n", false).unwrap();
  assert_eq!(std::fs::read_to_string(&shim).unwrap(), "# new\n");
  assert!(log.iter().any(|l| l.contains("updated")), "{log:?}");
  assert!(!log.iter().any(|l| l.contains("profile.ps1")), "profile already correct: {log:?}");
}

#[test]
fn the_profile_line_no_longer_invokes_devkit() {
  // The defect this change exists to remove: $PROFILE used to shell out at every shell
  // start just to obtain the script text.
  assert!(!POWERSHELL_LINE.contains("Invoke-Expression"));
  assert!(POWERSHELL_LINE.contains("poe-completion.ps1"));
}

#[test]
fn migrating_a_profile_replaces_the_previous_devkit_line() {
  let before = "Set-Alias ll Get-ChildItem\ndevkit complete script --powershell | Out-String | Invoke-Expression\n";
  let (text, log) = patch_profile(Some(before));
  assert!(!text.contains("Invoke-Expression"), "{text}");
  assert!(text.contains("poe-completion.ps1"), "{text}");
  assert!(text.contains("Set-Alias ll Get-ChildItem"), "the user's own lines survive");
  assert!(
    log.iter().any(|l| l.contains("removed the previous devkit registration")),
    "{log:?}"
  );
}

#[test]
fn install_powershell_dry_run_writes_nothing() {
  let dir = tempfile::tempdir().unwrap();
  let profile = dir.path().join("profile.ps1");
  let shim = powershell_shim_path(dir.path());
  let log = install_powershell(&profile, &shim, "# shim\n", true).unwrap();
  assert!(!log.is_empty());
  assert!(!profile.exists());
  assert!(!shim.exists());
}

#[test]
fn install_bash_writes_every_target_skips_foreign_files_and_is_idempotent() {
  let dir = tempfile::tempdir().unwrap();
  let git_bash = dir.path().join("bash_completion.d").join("poe.bash");
  let standard = dir.path().join("completions").join("poe");
  let foreign = dir.path().join("foreign").join("poe");
  std::fs::create_dir_all(foreign.parent().unwrap()).unwrap();
  std::fs::write(&foreign, "# mine\n").unwrap();

  let targets = vec![git_bash.clone(), standard.clone(), foreign.clone()];
  let log = install_bash(&targets, SCRIPT, false).unwrap();
  assert_eq!(std::fs::read_to_string(&git_bash).unwrap(), SCRIPT);
  assert_eq!(std::fs::read_to_string(&standard).unwrap(), SCRIPT);
  assert_eq!(
    std::fs::read_to_string(&foreign).unwrap(),
    "# mine\n",
    "foreign file must be untouched"
  );
  assert!(
    log.iter().any(|l| l.contains("foreign") && l.to_lowercase().contains("left")),
    "{log:?}"
  );

  let again = install_bash(&targets[..2], SCRIPT, false).unwrap();
  assert!(again.is_empty(), "{again:?}");
}

#[test]
fn install_bash_dry_run_writes_nothing() {
  let dir = tempfile::tempdir().unwrap();
  let target = dir.path().join("poe.bash");
  let log = install_bash(std::slice::from_ref(&target), SCRIPT, true).unwrap();
  assert!(!log.is_empty());
  assert!(!target.exists());
}

#[test]
fn migration_leaves_a_comment_mentioning_the_old_command_alone() {
  // A `contains` match would delete this line: it mentions the old registration but is a
  // note the user wrote, not a command the shell would run. $PROFILE is user-owned config.
  let before = "# old way: devkit complete script --powershell | Out-String | Invoke-Expression\n";
  let (text, log) = patch_profile(Some(before));
  assert!(
    text.contains("# old way: devkit complete script"),
    "the user's comment must survive: {text}"
  );
  assert!(
    !log.iter().any(|l| l.contains("removed")),
    "nothing should be reported as removed: {log:?}"
  );
}

#[test]
fn migration_still_removes_the_real_command_with_a_call_operator() {
  // `& devkit complete script ...` is an actual invocation, and `drop` strips the leading
  // `&` before matching, so it is still caught.
  let before = "& devkit complete script --powershell | Out-String | Invoke-Expression\n";
  let (text, log) = patch_profile(Some(before));
  assert!(!text.contains("Invoke-Expression"), "{text}");
  assert!(
    log.iter().any(|l| l.contains("removed the previous devkit registration")),
    "{log:?}"
  );
}
