use std::path::PathBuf;

use aeth_devkit_complete::install::{
  FileAction, POWERSHELL_LINE, bash_file_action, devkit_on_path, install_bash, install_powershell, patch_profile, powershell_profile,
};
use aeth_devkit_core::process::RecordingRunner;

// ---- PowerShell profile text ---------------------------------------------------------------

#[test]
fn missing_profile_becomes_just_the_devkit_line() {
  let (text, log) = patch_profile(None);
  assert_eq!(text, format!("{POWERSHELL_LINE}\n"));
  assert!(!log.is_empty());
}

#[test]
fn poes_line_is_replaced_and_other_lines_survive() {
  let original = "Set-Alias ll Get-ChildItem\npoe _powershell_completion | out-string | invoke-expression\nfunction x { }\n";
  let (text, log) = patch_profile(Some(original));
  assert_eq!(text, format!("Set-Alias ll Get-ChildItem\nfunction x {{ }}\n{POWERSHELL_LINE}\n"));
  assert!(log.iter().any(|l| l.contains("poe _powershell_completion")), "{log:?}");
  assert!(log.iter().any(|l| l.contains("added")), "{log:?}");
}

#[test]
fn profile_patch_is_idempotent_and_case_insensitive() {
  let (once, _) = patch_profile(Some("x\n"));
  let (twice, log) = patch_profile(Some(&once));
  assert_eq!(once, twice);
  assert!(log.is_empty(), "{log:?}");
  // A hand-typed variant with different casing still counts as present.
  let lower = format!("x\n{}\n", POWERSHELL_LINE.to_lowercase());
  let (text, log) = patch_profile(Some(&lower));
  assert_eq!(text, lower);
  assert!(log.is_empty(), "{log:?}");
}

#[test]
fn profile_patch_preserves_crlf_and_a_missing_trailing_newline() {
  let (text, _) = patch_profile(Some("a\r\npoe _powershell_completion | Out-String | Invoke-Expression\r\nb"));
  assert_eq!(text, format!("a\r\nb\r\n{POWERSHELL_LINE}\r\n"));
}

// ---- bash file decision --------------------------------------------------------------------

const SCRIPT: &str = "# Bash completion for poe\n# Generated by poethepoet, adapted by aeth-devkit: task data comes from `devkit complete`\ncomplete -F _poe_complete poe\n";

#[test]
fn bash_file_decisions() {
  assert_eq!(bash_file_action(None, SCRIPT), FileAction::Write);
  assert_eq!(bash_file_action(Some(SCRIPT), SCRIPT), FileAction::Unchanged);
  // poe's own generated file (what `poe _bash_completion > …/poe` leaves behind) is ours to replace.
  assert_eq!(
    bash_file_action(
      Some("# Bash completion for poe\n# Generated by poethepoet\n_poe_complete() { }\n"),
      SCRIPT
    ),
    FileAction::Write
  );
  // An older devkit-generated file too.
  assert_eq!(bash_file_action(Some("# adapted by aeth-devkit\nold\n"), SCRIPT), FileAction::Write);
  // Anything else is the user's.
  assert_eq!(
    bash_file_action(Some("# my own poe completion\ncomplete -W 'a b' poe\n"), SCRIPT),
    FileAction::RefuseForeign
  );
}

// ---- PATH check ----------------------------------------------------------------------------

#[test]
fn devkit_on_path_finds_exe_or_bare_name_in_any_entry() {
  let dir = tempfile::tempdir().unwrap();
  let sep = if cfg!(windows) { ";" } else { ":" };
  let empty_dir = tempfile::tempdir().unwrap();
  let path_var = format!("{}{sep}{}", empty_dir.path().display(), dir.path().display());
  assert_eq!(devkit_on_path(&path_var), None);
  std::fs::write(dir.path().join(if cfg!(windows) { "devkit.exe" } else { "devkit" }), "").unwrap();
  assert_eq!(
    devkit_on_path(&path_var).map(|p| p.parent().unwrap().to_path_buf()),
    Some(dir.path().to_path_buf())
  );
}

// ---- $PROFILE lookup -----------------------------------------------------------------------

#[test]
fn powershell_profile_asks_powershell_and_trims() {
  let r = RecordingRunner::new(0);
  r.script(
    "powershell",
    &["-NoProfile"],
    0,
    "C:\\Users\\me\\Documents\\WindowsPowerShell\\Microsoft.PowerShell_profile.ps1\r\n",
  );
  assert_eq!(
    powershell_profile(&r).unwrap(),
    PathBuf::from("C:\\Users\\me\\Documents\\WindowsPowerShell\\Microsoft.PowerShell_profile.ps1")
  );
  let failing = RecordingRunner::new(1);
  assert!(powershell_profile(&failing).is_err());
}

// ---- file-level installs -------------------------------------------------------------------

#[test]
fn install_powershell_creates_or_patches_the_profile_and_is_idempotent() {
  let dir = tempfile::tempdir().unwrap();
  let profile = dir.path().join("WindowsPowerShell").join("profile.ps1");
  let log = install_powershell(&profile, false).unwrap();
  assert!(!log.is_empty());
  assert_eq!(std::fs::read_to_string(&profile).unwrap(), format!("{POWERSHELL_LINE}\n"));
  assert!(
    install_powershell(&profile, false).unwrap().is_empty(),
    "second run must be a no-op"
  );
}

#[test]
fn install_powershell_dry_run_writes_nothing() {
  let dir = tempfile::tempdir().unwrap();
  let profile = dir.path().join("profile.ps1");
  let log = install_powershell(&profile, true).unwrap();
  assert!(!log.is_empty());
  assert!(!profile.exists());
}

#[test]
fn install_bash_writes_every_target_skips_foreign_files_and_is_idempotent() {
  let dir = tempfile::tempdir().unwrap();
  let git_bash = dir.path().join("bash_completion.d").join("poe.bash");
  let standard = dir.path().join("completions").join("poe");
  let foreign = dir.path().join("foreign").join("poe");
  std::fs::create_dir_all(foreign.parent().unwrap()).unwrap();
  std::fs::write(&foreign, "# mine\n").unwrap();

  let targets = vec![git_bash.clone(), standard.clone(), foreign.clone()];
  let log = install_bash(&targets, SCRIPT, false).unwrap();
  assert_eq!(std::fs::read_to_string(&git_bash).unwrap(), SCRIPT);
  assert_eq!(std::fs::read_to_string(&standard).unwrap(), SCRIPT);
  assert_eq!(
    std::fs::read_to_string(&foreign).unwrap(),
    "# mine\n",
    "foreign file must be untouched"
  );
  assert!(
    log.iter().any(|l| l.contains("foreign") && l.to_lowercase().contains("left")),
    "{log:?}"
  );

  let again = install_bash(&targets[..2], SCRIPT, false).unwrap();
  assert!(again.is_empty(), "{again:?}");
}

#[test]
fn install_bash_dry_run_writes_nothing() {
  let dir = tempfile::tempdir().unwrap();
  let target = dir.path().join("poe.bash");
  let log = install_bash(std::slice::from_ref(&target), SCRIPT, true).unwrap();
  assert!(!log.is_empty());
  assert!(!target.exists());
}

// ---- preflight -----------------------------------------------------------------------------

#[test]
fn preflight_refuses_when_devkit_is_not_on_path_and_says_how_to_fix_it() {
  let empty = tempfile::tempdir().unwrap();
  let err = aeth_devkit_complete::install::preflight(&empty.path().display().to_string()).unwrap_err();
  assert!(err.to_string().contains("uv tool install aeth-devkit"), "{err}");
}

#[test]
fn preflight_warns_when_the_only_devkit_is_inside_a_venv() {
  let dir = tempfile::tempdir().unwrap();
  let scripts = dir.path().join(".venv").join("Scripts");
  std::fs::create_dir_all(&scripts).unwrap();
  std::fs::write(scripts.join(if cfg!(windows) { "devkit.exe" } else { "devkit" }), "").unwrap();
  let warning = aeth_devkit_complete::install::preflight(&scripts.display().to_string()).unwrap();
  assert!(warning.is_some_and(|w| w.contains(".venv")), "expected a venv warning");
}

#[test]
fn preflight_is_silent_for_a_global_devkit() {
  let dir = tempfile::tempdir().unwrap();
  std::fs::write(dir.path().join(if cfg!(windows) { "devkit.exe" } else { "devkit" }), "").unwrap();
  assert_eq!(
    aeth_devkit_complete::install::preflight(&dir.path().display().to_string()).unwrap(),
    None
  );
}

/// poe writes its completion file through the Windows console codepage, so an em dash in its
/// comments arrives as a lone 0x97 byte and the file is not valid UTF-8. It is still a
/// generated file and must be replaced, not treated as an error.
#[test]
fn install_bash_replaces_a_non_utf8_poe_generated_file() {
  let dir = tempfile::tempdir().unwrap();
  let target = dir.path().join("poe");
  let mut bytes = b"# Bash completion for poe\n# Generated by poethepoet\n# em dash: ".to_vec();
  bytes.push(0x97);
  bytes.extend_from_slice(b"\ncomplete -F _poe_complete poe\n");
  std::fs::write(&target, &bytes).unwrap();
  let log = install_bash(std::slice::from_ref(&target), SCRIPT, false).unwrap();
  assert!(log.iter().any(|l| l.contains("updated")), "{log:?}");
  assert_eq!(std::fs::read_to_string(&target).unwrap(), SCRIPT);
}
