//! `devkit complete install` — wire the completion scripts into the user's shells.
//!
//! PowerShell gets one line in `$PROFILE` that evaluates the script at shell start (there
//! is no completions-directory convention to use instead). bash gets a *file*, following
//! poe's own documented install: `~/bash_completion.d/poe.bash`, which Git Bash sources from
//! `/etc/profile.d/git-prompt.sh`, and `~/.local/share/bash-completion/completions/poe`, the
//! standard location the `bash-completion` package reads on Linux. Both files hold the same
//! text; writing both means the install works whichever loader the shell has.

use std::path::{Path, PathBuf};

use anyhow::{Context as _, Result, bail};

use aeth_devkit_core::process::Runner;

/// The line `install --powershell` puts in `$PROFILE`.
pub const POWERSHELL_LINE: &str = "devkit complete script --powershell | Out-String | Invoke-Expression";

/// Fragment identifying poe's own registration line, which devkit's replaces: both register
/// for the `poe` command and the last one loaded wins, so keeping poe's would only pay its
/// ~200 ms Python start at every shell launch for nothing.
const POE_POWERSHELL_LINE: &str = "poe _powershell_completion";

/// Header fragments marking a bash completion file as generated — by poe or by devkit — and
/// therefore ours to overwrite. Anything else was written by a person.
const GENERATED_MARKERS: [&str; 2] = ["Generated by poethepoet", "adapted by aeth-devkit"];

/// What to do with a bash completion file that may already exist.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FileAction {
  /// Already holds exactly this script.
  Unchanged,
  /// Missing, or a poe/devkit-generated file we may overwrite.
  Write,
  /// Something the user wrote themselves; leave it alone.
  RefuseForeign,
}

/// Rewrite a PowerShell profile: drop poe's own registration line, add devkit's if absent.
/// Returns the new text and a log of what changed (empty when nothing did).
pub fn patch_profile(original: Option<&str>) -> (String, Vec<String>) {
  let original = original.unwrap_or("");
  let eol = if original.contains("\r\n") { "\r\n" } else { "\n" };
  let mut log = Vec::new();
  let mut lines: Vec<&str> = Vec::new();
  let mut present = false;
  for line in original.lines() {
    let t = line.trim();
    let drop = t.trim_start_matches('&').trim_start().to_ascii_lowercase();
    if drop.starts_with(POE_POWERSHELL_LINE) {
      log.push(format!("removed poe's own registration: {t}"));
      continue;
    }
    // Case-insensitive so a hand-typed variant (`out-string | invoke-expression`) counts.
    if t.eq_ignore_ascii_case(POWERSHELL_LINE) {
      present = true;
    }
    lines.push(line);
  }
  if !present {
    lines.push(POWERSHELL_LINE);
    log.push(format!("added: {POWERSHELL_LINE}"));
  }
  let mut text = lines.join(eol);
  text.push_str(eol);
  // Nothing changed → hand back the original byte-for-byte (a file that lacked a trailing
  // newline stays that way), so callers can compare and skip the write.
  if log.is_empty() { (original.to_string(), log) } else { (text, log) }
}

/// Decide what to do with a bash completion file given its current content.
pub fn bash_file_action(existing: Option<&str>, script: &str) -> FileAction {
  match existing {
    None => FileAction::Write,
    Some(text) if text == script => FileAction::Unchanged,
    // Only the header is inspected: a user file that merely mentions poe further down is
    // still theirs.
    Some(text) if text.lines().take(5).any(|l| GENERATED_MARKERS.iter().any(|m| l.contains(m))) => FileAction::Write,
    Some(_) => FileAction::RefuseForeign,
  }
}

/// Where `devkit` resolves from the given `PATH` value, if anywhere.
pub fn devkit_on_path(path_var: &str) -> Option<PathBuf> {
  std::env::split_paths(path_var).find_map(|dir| ["devkit.exe", "devkit"].into_iter().map(|n| dir.join(n)).find(|p| p.is_file()))
}

/// Ask PowerShell where its profile lives, rather than guessing the Documents path.
pub fn powershell_profile(runner: &dyn Runner) -> Result<PathBuf> {
  let args = ["-NoProfile", "-NonInteractive", "-Command", "$PROFILE"].map(str::to_string);
  let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
  let out = runner
    .run_capture("powershell", &args, &cwd)
    .context("running powershell to find $PROFILE")?;
  let path = out.stdout.trim();
  if !out.success() || path.is_empty() {
    bail!("could not determine the PowerShell profile path: {}", out.stderr.trim());
  }
  Ok(PathBuf::from(path))
}

/// Install into `profile` (created if missing). Returns the change log.
pub fn install_powershell(profile: &Path, dry_run: bool) -> Result<Vec<String>> {
  let original = match std::fs::read_to_string(profile) {
    Ok(s) => Some(s),
    Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
    Err(e) => return Err(e).with_context(|| format!("reading {}", profile.display())),
  };
  let (text, mut log) = patch_profile(original.as_deref());
  if log.is_empty() {
    return Ok(log);
  }
  if original.is_none() {
    log.insert(0, format!("created {}", profile.display()));
  } else {
    log.insert(0, format!("updated {}", profile.display()));
  }
  if !dry_run {
    if let Some(dir) = profile.parent() {
      std::fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
    }
    std::fs::write(profile, text).with_context(|| format!("writing {}", profile.display()))?;
  }
  Ok(log)
}

/// Write `script` to each of `files` (parents created), honouring [`bash_file_action`].
pub fn install_bash(files: &[PathBuf], script: &str, dry_run: bool) -> Result<Vec<String>> {
  let mut log = Vec::new();
  for file in files {
    // Read bytes and decode lossily: poe writes this file through the Windows console
    // codepage, so its em dashes arrive as lone 0x97 bytes and the file is not valid UTF-8.
    // The header we key on is ASCII, so a lossy decode still identifies it as generated.
    let existing = match std::fs::read(file) {
      Ok(bytes) => Some(String::from_utf8_lossy(&bytes).into_owned()),
      Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
      Err(e) => return Err(e).with_context(|| format!("reading {}", file.display())),
    };
    match bash_file_action(existing.as_deref(), script) {
      FileAction::Unchanged => {}
      FileAction::RefuseForeign => {
        log.push(format!(
          "left {} alone: not a generated file (remove it by hand to replace it)",
          file.display()
        ));
      }
      FileAction::Write => {
        log.push(format!(
          "{} {}",
          if existing.is_some() { "updated" } else { "created" },
          file.display()
        ));
        if !dry_run {
          if let Some(dir) = file.parent() {
            std::fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
          }
          std::fs::write(file, script).with_context(|| format!("writing {}", file.display()))?;
        }
      }
    }
  }
  Ok(log)
}

/// Check that a profile line invoking bare `devkit` will actually resolve in a fresh shell.
/// `Err` carries the instruction to print; `Ok(Some(_))` is a warning to print and proceed.
pub fn preflight(path_var: &str) -> Result<Option<String>> {
  let Some(found) = devkit_on_path(path_var) else {
    bail!(
      "`devkit` is not on PATH, so a profile line calling it would break every new shell.\n\
       Install it globally the same way poe is: `uv tool install aeth-devkit --index <your index url>`,\n\
       then re-run this command."
    );
  };
  // A venv's Scripts dir is on PATH only while that venv is activated; a fresh shell won't
  // have it. Proceed — the user may have arranged PATH deliberately — but say so.
  let in_venv = found.components().any(|c| c.as_os_str() == ".venv");
  Ok(in_venv.then(|| {
    format!(
      "warning: the `devkit` on PATH is inside a .venv ({}); completion will only work in shells where that venv is on PATH. \
       For a global install: `uv tool install aeth-devkit --index <your index url>`.",
      found.display()
    )
  }))
}
