//! `devkit complete install` — wire the completion scripts into the user's shells.
//!
//! PowerShell gets one line in `$PROFILE` that evaluates the script at shell start (there
//! is no completions-directory convention to use instead). bash gets a *file*, following
//! poe's own documented install: `~/bash_completion.d/poe.bash`, which Git Bash sources from
//! `/etc/profile.d/git-prompt.sh`, and `~/.local/share/bash-completion/completions/poe`, the
//! standard location the `bash-completion` package reads on Linux. Both files hold the same
//! text; writing both means the install works whichever loader the shell has.

use std::path::{Path, PathBuf};

use anyhow::{Context as _, Result, bail};

use aeth_devkit_core::process::Runner;

/// The line `install --powershell` puts in `$PROFILE`.
///
/// Deliberately content-free: it names a path and nothing else. Because it never needs to
/// change, the only artifact that can ever drift is the shim file itself — which devkit owns
/// and may safely rewrite, unlike the user's profile.
pub const POWERSHELL_LINE: &str = "$c = \"$HOME/.local/share/devkit/poe-completion.ps1\"; if (Test-Path $c) { . $c }";

/// Fragment identifying the *previous* devkit registration, which this one replaces. That
/// line ran devkit at every shell start merely to fetch the script text, which is precisely
/// what made a global install mandatory.
const OLD_DEVKIT_POWERSHELL_LINE: &str = "devkit complete script --powershell";

/// Fragment identifying poe's own registration line, which devkit's replaces: both register
/// for the `poe` command and the last one loaded wins, so keeping poe's would only pay its
/// ~200 ms Python start at every shell launch for nothing.
const POE_POWERSHELL_LINE: &str = "poe _powershell_completion";

/// Header fragments marking a bash completion file as generated — by poe or by devkit — and
/// therefore ours to overwrite. Anything else was written by a person.
const GENERATED_MARKERS: [&str; 2] = ["Generated by poethepoet", "adapted by aeth-devkit"];

/// What to do with a bash completion file that may already exist.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum FileAction {
  /// Already holds exactly this script.
  Unchanged,
  /// Missing, or a poe/devkit-generated file we may overwrite.
  Write,
  /// Something the user wrote themselves; leave it alone.
  RefuseForeign,
}

/// Rewrite a PowerShell profile: drop poe's own registration line, add devkit's if absent.
/// Returns the new text and a log of what changed (empty when nothing did).
pub fn patch_profile(original: Option<&str>) -> (String, Vec<String>) {
  let original = original.unwrap_or("");
  let eol = if original.contains("\r\n") { "\r\n" } else { "\n" };
  let mut log = Vec::new();
  let mut lines: Vec<&str> = Vec::new();
  let mut present = false;
  for line in original.lines() {
    let t = line.trim();
    let drop = t.trim_start_matches('&').trim_start().to_ascii_lowercase();
    if drop.starts_with(POE_POWERSHELL_LINE) {
      log.push(format!("removed poe's own registration: {t}"));
      continue;
    }
    // Migration: an earlier devkit put a line here that shelled out at every shell start.
    //
    // `starts_with` on the normalised form, not `contains` on the raw line: a `contains`
    // would also match a line that merely mentions the command -- a commented-out note or
    // an instruction in the user's own profile -- and silently delete it. `drop` has
    // already stripped a leading `&` and lowercased, so both call-operator and
    // differently-cased spellings still match.
    if drop.starts_with(OLD_DEVKIT_POWERSHELL_LINE) {
      log.push(format!("removed the previous devkit registration: {t}"));
      continue;
    }
    // Case-insensitive so a hand-typed variant (`out-string | invoke-expression`) counts.
    if t.eq_ignore_ascii_case(POWERSHELL_LINE) {
      present = true;
    }
    lines.push(line);
  }
  if !present {
    lines.push(POWERSHELL_LINE);
    log.push(format!("added: {POWERSHELL_LINE}"));
  }
  let mut text = lines.join(eol);
  text.push_str(eol);
  // Nothing changed → hand back the original byte-for-byte (a file that lacked a trailing
  // newline stays that way), so callers can compare and skip the write.
  if log.is_empty() { (original.to_string(), log) } else { (text, log) }
}

/// Decide what to do with a bash completion file given its current content.
pub fn bash_file_action(existing: Option<&str>, script: &str) -> FileAction {
  match existing {
    None => FileAction::Write,
    Some(text) if text == script => FileAction::Unchanged,
    // Only the header is inspected: a user file that merely mentions poe further down is
    // still theirs.
    Some(text) if text.lines().take(5).any(|l| GENERATED_MARKERS.iter().any(|m| l.contains(m))) => FileAction::Write,
    Some(_) => FileAction::RefuseForeign,
  }
}

/// Where the PowerShell shim is written.
///
/// Mirrors the `~/.local/share` convention the bash targets already use, so both shells keep
/// their generated file in the same place rather than one hiding in the profile itself.
pub fn powershell_shim_path(home: &Path) -> PathBuf {
  home.join(".local").join("share").join("devkit").join("poe-completion.ps1")
}

/// Ask PowerShell where its profile lives, rather than guessing the Documents path.
pub fn powershell_profile(runner: &dyn Runner) -> Result<PathBuf> {
  let args = ["-NoProfile", "-NonInteractive", "-Command", "$PROFILE"].map(str::to_string);
  let cwd = std::env::current_dir().unwrap_or_else(|_| PathBuf::from("."));
  let out = runner
    .run_capture("powershell", &args, &cwd)
    .context("running powershell to find $PROFILE")?;
  let path = out.stdout.trim();
  if !out.success() || path.is_empty() {
    bail!("could not determine the PowerShell profile path: {}", out.stderr.trim());
  }
  Ok(PathBuf::from(path))
}

/// Install into `profile` (created if missing), writing the shim file it points at.
///
/// Two artifacts, deliberately separate: `script` goes to `shim_path`, which devkit owns and
/// rewrites freely, while `profile` gets one permanent line and is otherwise the user's.
pub fn install_powershell(profile: &Path, shim_path: &Path, script: &str, dry_run: bool) -> Result<Vec<String>> {
  let mut log = install_shim_file(shim_path, script, dry_run)?;
  log.extend(install_profile_line(profile, dry_run)?);
  Ok(log)
}

/// Write the shim script, unless it is already byte-identical.
fn install_shim_file(shim_path: &Path, script: &str, dry_run: bool) -> Result<Vec<String>> {
  // `Ok(text)` when readable, `None` when absent; any other error is a real problem and
  // propagates rather than being silently treated as "missing".
  let existing = match std::fs::read_to_string(shim_path) {
    Ok(text) => Some(text),
    Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
    Err(e) => return Err(e).with_context(|| format!("reading {}", shim_path.display())),
  };
  if existing.as_deref() == Some(script) {
    return Ok(Vec::new());
  }
  let verb = if existing.is_some() { "updated" } else { "created" };
  if !dry_run {
    if let Some(dir) = shim_path.parent() {
      std::fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
    }
    std::fs::write(shim_path, script).with_context(|| format!("writing {}", shim_path.display()))?;
  }
  Ok(vec![format!("{verb} {}", shim_path.display())])
}

/// Add devkit's line to `profile` (created if missing). Returns the change log.
fn install_profile_line(profile: &Path, dry_run: bool) -> Result<Vec<String>> {
  let original = match std::fs::read_to_string(profile) {
    Ok(s) => Some(s),
    Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
    Err(e) => return Err(e).with_context(|| format!("reading {}", profile.display())),
  };
  let (text, mut log) = patch_profile(original.as_deref());
  if log.is_empty() {
    return Ok(log);
  }
  if original.is_none() {
    log.insert(0, format!("created {}", profile.display()));
  } else {
    log.insert(0, format!("updated {}", profile.display()));
  }
  if !dry_run {
    if let Some(dir) = profile.parent() {
      std::fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
    }
    std::fs::write(profile, text).with_context(|| format!("writing {}", profile.display()))?;
  }
  Ok(log)
}

/// Write `script` to each of `files` (parents created), honouring [`bash_file_action`].
pub fn install_bash(files: &[PathBuf], script: &str, dry_run: bool) -> Result<Vec<String>> {
  let mut log = Vec::new();
  for file in files {
    // Read bytes and decode lossily: poe writes this file through the Windows console
    // codepage, so its em dashes arrive as lone 0x97 bytes and the file is not valid UTF-8.
    // The header we key on is ASCII, so a lossy decode still identifies it as generated.
    let existing = match std::fs::read(file) {
      Ok(bytes) => Some(String::from_utf8_lossy(&bytes).into_owned()),
      Err(e) if e.kind() == std::io::ErrorKind::NotFound => None,
      Err(e) => return Err(e).with_context(|| format!("reading {}", file.display())),
    };
    match bash_file_action(existing.as_deref(), script) {
      FileAction::Unchanged => {}
      FileAction::RefuseForeign => {
        log.push(format!(
          "left {} alone: not a generated file (remove it by hand to replace it)",
          file.display()
        ));
      }
      FileAction::Write => {
        log.push(format!(
          "{} {}",
          if existing.is_some() { "updated" } else { "created" },
          file.display()
        ));
        if !dry_run {
          if let Some(dir) = file.parent() {
            std::fs::create_dir_all(dir).with_context(|| format!("creating {}", dir.display()))?;
          }
          std::fs::write(file, script).with_context(|| format!("writing {}", file.display()))?;
        }
      }
    }
  }
  Ok(log)
}

/// The bash completion files, in the order they are written. Both hold the same script;
/// see the module doc in [`install`] for why there are two.
pub fn bash_targets(home: &Path) -> Vec<PathBuf> {
  vec![
    home.join("bash_completion.d").join("poe.bash"),
    home
      .join(".local")
      .join("share")
      .join("bash-completion")
      .join("completions")
      .join("poe"),
  ]
}
