//! Shell completion scripts: poe's own generated scripts with the two per-Tab data calls
//! (`poe _list_tasks`, `poe _describe_task_args`) swapped for `devkit complete tasks` /
//! `devkit complete args`. Everything else — global option lists, `-C` handling, `--`
//! pass-through, choice completion — is poe's, verbatim, so behaviour is identical and only
//! the data source is faster.
//!
//! Regenerate with `scratchpad/gen_scripts.py` when poe's generator changes.

/// `devkit complete script --powershell`; add to `$PROFILE` via `| Out-String | Invoke-Expression`.
pub const POWERSHELL: &str = r##"# PowerShell completion for poe
# Generated by poethepoet, adapted by aeth-devkit: task data comes from `devkit complete`
#
# To enable, add to your PowerShell profile ($PROFILE):
#   devkit complete script --powershell | Out-String | Invoke-Expression

$script:PoeGlobalOptions = @('-h', '--help', '--version', '-v', '--verbose', '-q', '--quiet', '-d', '--dry-run', '-C', '--directory', '-e', '--executor', '-X', '--executor-opt', '--ansi', '--no-ansi')
$script:PoeOptionsWithValues = @('-h', '--help', '-C', '--directory', '-e', '--executor', '-X', '--executor-opt')
$script:PoeGlobalOptionExclusions = @{
    '-h' = @('--help', '-h')
    '--help' = @('--help', '-h')
    '--version' = @('--version')
    '-v' = @('--quiet', '-q')
    '--verbose' = @('--quiet', '-q')
    '-q' = @('--verbose', '-v')
    '--quiet' = @('--verbose', '-v')
    '-d' = @('--dry-run', '-d')
    '--dry-run' = @('--dry-run', '-d')
    '-C' = @('--directory', '-C')
    '--directory' = @('--directory', '-C')
    '-e' = @('--executor', '-e')
    '--executor' = @('--executor', '-e')
    '-X' = @()
    '--executor-opt' = @()
    '--ansi' = @('--ansi', '--no-ansi')
    '--no-ansi' = @('--ansi', '--no-ansi')
}

function script:Get-PoeTargetPath {
    param([string[]]$Words)

    for ($i = 1; $i -lt $Words.Count; $i++) {
        $w = $Words[$i]
        if ($w.StartsWith('-')) {
            # Handle --opt=value: extract base option and inline value
            $optBase = if ($w.Contains('=')) { $w.Substring(0, $w.IndexOf('=')) } else { $w }
            $hasEquals = $w.Contains('=')
            if ($optBase -in @('-C', '--directory', '--root')) {
                if ($hasEquals) {
                    return $w.Substring($w.IndexOf('=') + 1)
                } elseif ($i + 1 -lt $Words.Count) {
                    return $Words[$i + 1]
                }
            }
            # Skip value for options that take values (only if no =)
            if (-not $hasEquals -and $optBase -in $script:PoeOptionsWithValues -and ($i + 1) -lt $Words.Count) { $i++ }
        } else {
            # First non-option word is the task — stop scanning global options
            break
        }
    }
    return $null
}

function script:Get-PoeCurrentTask {
    param([string[]]$Words)

    for ($i = 1; $i -lt $Words.Count; $i++) {
        $word = $Words[$i]
        # Skip options
        if ($word.StartsWith('-')) {
            $optBase = if ($word.Contains('=')) { $word.Substring(0, $word.IndexOf('=')) } else { $word }
            $hasEquals = $word.Contains('=')
            # Skip value for options that take values (only if no =)
            if (-not $hasEquals -and $optBase -in $script:PoeOptionsWithValues -and ($i + 1) -lt $Words.Count) { $i++ }
            continue
        }
        # First non-option word is the task
        return $word
    }
    return $null
}

function script:Get-PoeTaskArgs {
    param(
        [string]$TaskName,
        [string]$TargetPath
    )

    if (-not $TaskName) {
        return @()
    }

    $taskArgList = @()
    try {
        $output = if ($TargetPath) {
            & devkit complete args $TaskName $TargetPath 2>$null
        } else {
            & devkit complete args $TaskName 2>$null
        }

        if ($output) {
            foreach ($line in $output -split "`n") {
                $parts = $line -split "`t"
                if ($parts.Count -ge 4) {
                    $taskArgList += @{
                        Options = $parts[0] -split ','
                        Type = $parts[1]
                        Help = $parts[2]
                        Choices = if ($parts[3] -eq '_') { @() } else { $parts[3] -split ' ' }
                    }
                }
            }
        }
    } catch {
        # Silently fail
    }
    return $taskArgList
}

function script:Get-PoeTasks {
    param([string]$TargetPath)

    try {
        $output = if ($TargetPath) {
            & devkit complete tasks $TargetPath 2>$null
        } else {
            & devkit complete tasks 2>$null
        }

        if ($output) {
            return $output -split ' ' | Where-Object { $_ }
        }
    } catch {
        # Silently fail
    }
    return @()
}

function script:Get-UsedOptions {
    param(
        [string[]]$Words,
        [int]$TaskPosition
    )

    $used = @{}
    for ($i = $TaskPosition + 1; $i -lt $Words.Count; $i++) {
        $word = $Words[$i]
        if ($word.StartsWith('-')) {
            $used[$word] = $true
        }
    }
    return $used
}

Register-ArgumentCompleter -CommandName poe -Native -ScriptBlock {
    param($wordToComplete, $commandAst, $cursorPosition)

    $words = $commandAst.CommandElements | ForEach-Object { $_.Extent.Text }
    $curWord = $wordToComplete

    # Get target path from -C/--directory/--root
    $targetPath = Get-PoeTargetPath -Words $words

    # Find the current task (first non-option word after command)
    $currentTask = $null
    $taskPosition = -1
    for ($i = 1; $i -lt $words.Count; $i++) {
        $word = $words[$i]
        if ($word.StartsWith('-')) {
            $optBase = if ($word.Contains('=')) { $word.Substring(0, $word.IndexOf('=')) } else { $word }
            $hasEquals = $word.Contains('=')
            # Skip value for options that take values (only if no =)
            if (-not $hasEquals -and $optBase -in $script:PoeOptionsWithValues -and ($i + 1) -lt $words.Count) { $i++ }
            continue
        }
        $currentTask = $word
        $taskPosition = $i
        break
    }

    # Determine cursor position in tokens
    $cursorIndex = $words.Count - 1
    if ($wordToComplete -eq '') {
        $cursorIndex = $words.Count
    }

    # Check for -- separator after task position
    $afterSeparator = $false
    if ($taskPosition -ge 0) {
        for ($j = $taskPosition + 1; $j -lt $words.Count; $j++) {
            if ($words[$j] -eq '--' -and $j -lt $cursorIndex) {
                $afterSeparator = $true
                break
            }
        }
    }

    # After --, only offer file completions (pass-through args to task)
    if ($afterSeparator) {
        Get-ChildItem -Path "$curWord*" -ErrorAction SilentlyContinue |
            ForEach-Object {
                $type = if ($_.PSIsContainer) { 'ProviderContainer' } else { 'ProviderItem' }
                [System.Management.Automation.CompletionResult]::new(
                    $_.FullName, $_.Name, $type, $_.FullName
                )
            }
        return
    }

    # Handle global option value completion — only before the task
    if ($wordToComplete -eq '' -and $words.Count -ge 1) { $prevWord = $words[-1] }
    elseif ($words.Count -ge 2) { $prevWord = $words[-2] }
    else { $prevWord = $null }

    # Handle --opt=value style for global options
    if ((-not $currentTask -or $cursorIndex -le $taskPosition) -and $curWord -like '-*=*') {
        $eqIdx = $curWord.IndexOf('=')
        $optPart = $curWord.Substring(0, $eqIdx)
        $valPart = $curWord.Substring($eqIdx + 1)
        $prefix = "$optPart="

        if ($optPart -in @('-C', '--directory', '--root')) {
            Get-ChildItem -Path "$valPart*" -Directory -ErrorAction SilentlyContinue |
                ForEach-Object {
                    [System.Management.Automation.CompletionResult]::new(
                        "$prefix$($_.FullName)", $_.Name, 'ParameterValue', $_.FullName
                    )
                }
            return
        }
        if ($optPart -in @('-e', '--executor')) {
            @('auto', 'poetry', 'simple', 'uv', 'virtualenv') |
                Where-Object { $_ -like "$valPart*" } |
                ForEach-Object {
                    [System.Management.Automation.CompletionResult]::new(
                        "$prefix$_", $_, 'ParameterValue', "Executor: $_"
                    )
                }
            return
        }
    }

    if ($prevWord -and (-not $currentTask -or $cursorIndex -le $taskPosition)) {
        switch ($prevWord) {
            { $_ -in @('-C', '--directory', '--root') } {
                # Directory completion
                Get-ChildItem -Path "$curWord*" -Directory -ErrorAction SilentlyContinue |
                    ForEach-Object {
                        [System.Management.Automation.CompletionResult]::new(
                            $_.FullName,
                            $_.Name,
                            'ParameterValue',
                            $_.FullName
                        )
                    }
                return
            }
            { $_ -in @('-e', '--executor') } {
                @('auto', 'poetry', 'simple', 'uv', 'virtualenv') |
                    Where-Object { $_ -like "$curWord*" } |
                    ForEach-Object {
                        [System.Management.Automation.CompletionResult]::new(
                            $_,
                            $_,
                            'ParameterValue',
                            "Executor: $_"
                        )
                    }
                return
            }
        }
    }

    # If we haven't found a task yet, or cursor is at/before task position
    if (-not $currentTask -or $cursorIndex -le $taskPosition) {
        # Complete global options if word starts with -
        if ($curWord.StartsWith('-')) {
            $excludedGlobalOpts = @{}
            for ($j = 1; $j -lt $words.Count; $j++) {
                $w = $words[$j]
                $optBase = if ($w.Contains('=')) { $w.Substring(0, $w.IndexOf('=')) } else { $w }
                if ($optBase.StartsWith('-') -and $script:PoeGlobalOptionExclusions.ContainsKey($optBase)) {
                    foreach ($ex in $script:PoeGlobalOptionExclusions[$optBase]) {
                        $excludedGlobalOpts[$ex] = $true
                    }
                }
            }
            $script:PoeGlobalOptions |
                Where-Object { $_ -like "$curWord*" -and -not $excludedGlobalOpts.ContainsKey($_) } |
                ForEach-Object {
                    [System.Management.Automation.CompletionResult]::new(
                        $_,
                        $_,
                        'ParameterName',
                        "Global option: $_"
                    )
                }
            return
        }

        # Complete task names
        $tasks = Get-PoeTasks -TargetPath $targetPath
        $tasks |
            Where-Object { $_ -like "$curWord*" } |
            ForEach-Object {
                [System.Management.Automation.CompletionResult]::new(
                    $_,
                    $_,
                    'Command',
                    "Task: $_"
                )
            }
        return
    }

    # We're past the task - complete task-specific args
    $taskArgs = Get-PoeTaskArgs -TaskName $currentTask -TargetPath $targetPath
    $usedOpts = Get-UsedOptions -Words $words -TaskPosition $taskPosition

    # Handle --opt=value style for task options
    if ($curWord -like '-*=*') {
        $eqIdx = $curWord.IndexOf('=')
        $optPart = $curWord.Substring(0, $eqIdx)
        $valPart = $curWord.Substring($eqIdx + 1)
        $prefix = "$optPart="
        foreach ($arg in $taskArgs) {
            if ($optPart -in $arg.Options) {
                if ($arg.Choices.Count -gt 0) {
                    $arg.Choices | Where-Object { $_ -like "$valPart*" } | ForEach-Object {
                        $value = $_ -replace "^'|'$", ""
                        [System.Management.Automation.CompletionResult]::new(
                            "$prefix$value", $value, 'ParameterValue', $value
                        )
                    }
                }
                return
            }
        }
        return
    }

    # If previous word is an option, try to complete its value
    if ($prevWord -and $prevWord.StartsWith('-')) {
        foreach ($arg in $taskArgs) {
            if ($prevWord -in $arg.Options) {
                if ($arg.Type -eq 'boolean') {
                    # Boolean flag - show remaining task options
                    break
                }
                if ($arg.Choices.Count -gt 0) {
                    $arg.Choices |
                        Where-Object { $_ -like "$curWord*" } |
                        ForEach-Object {
                            # Remove surrounding quotes if present
                            $value = $_ -replace "^'|'$", ""
                            [System.Management.Automation.CompletionResult]::new(
                                $value,
                                $value,
                                'ParameterValue',
                                $value
                            )
                        }
                    return
                }
                # No choices - don't offer completions for free-form text
                # Let the user type their custom value without interference
                return
            }
        }
    }

    # Show task options if word starts with -
    if ($curWord.StartsWith('-')) {
        # Build list of all option strings, excluding already used ones
        # Only scan words after the task position to avoid global options
        $usedGroups = @{}
        for ($j = $taskPosition + 1; $j -lt $words.Count; $j++) {
            $w = $words[$j]
            if (-not $w.StartsWith('-')) { continue }
            $optBase = if ($w.Contains('=')) { $w.Substring(0, $w.IndexOf('=')) } else { $w }
            foreach ($arg in $taskArgs) {
                if ($optBase -in $arg.Options) {
                    foreach ($opt in $arg.Options) {
                        $usedGroups[$opt] = $true
                    }
                }
            }
        }

        foreach ($arg in $taskArgs) {
            if ($arg.Type -eq 'positional') { continue }
            foreach ($opt in $arg.Options) {
                if ($usedGroups.ContainsKey($opt)) { continue }
                if ($opt -like "$curWord*") {
                    $helpText = if ($arg.Help -and $arg.Help -ne ' ') { $arg.Help } else { "Option: $opt" }
                    [System.Management.Automation.CompletionResult]::new(
                        $opt,
                        $opt,
                        'ParameterName',
                        $helpText
                    )
                }
            }
        }
        return
    }

    # Try positional argument choices
    $positionalIndex = 0
    for ($i = $taskPosition + 1; $i -lt $words.Count; $i++) {
        $word = $words[$i]
        if ($word.StartsWith('-')) {
            $optBase = if ($word.Contains('=')) { $word.Substring(0, $word.IndexOf('=')) } else { $word }
            $hasEquals = $word.Contains('=')
            # Check if this is a known option with value
            $isValuedOpt = $false
            foreach ($arg in $taskArgs) {
                if ($optBase -in $arg.Options -and $arg.Type -ne 'boolean') {
                    $isValuedOpt = $true
                    break
                }
            }
            if ($isValuedOpt -and -not $hasEquals) { $i++ }
            continue
        }
        # This is a positional arg (or the current word we're completing)
        if ($i -lt ($words.Count - 1) -or $wordToComplete -eq '') {
            $positionalIndex++
        }
    }

    # Find positional arg at this index
    # Wrap in @() to ensure it's always an array (Where-Object returns single item directly)
    $positionalArgs = @($taskArgs | Where-Object { $_.Type -eq 'positional' })
    if ($positionalIndex -lt $positionalArgs.Count) {
        $posArg = $positionalArgs[$positionalIndex]
        if ($posArg.Choices.Count -gt 0) {
            $posArg.Choices |
                Where-Object { $_ -like "$curWord*" } |
                ForEach-Object {
                    $value = $_ -replace "^'|'$", ""
                    [System.Management.Automation.CompletionResult]::new(
                        $value,
                        $value,
                        'ParameterValue',
                        $value
                    )
                }
            return
        }
    }

    # Fall back to file completion
    Get-ChildItem -Path "$curWord*" -ErrorAction SilentlyContinue |
        ForEach-Object {
            $type = if ($_.PSIsContainer) { 'ProviderContainer' } else { 'ProviderItem' }
            [System.Management.Automation.CompletionResult]::new(
                $_.FullName,
                $_.Name,
                $type,
                $_.FullName
            )
        }
}

"##;

/// `devkit complete script --bash`; `source <(devkit complete script --bash)` from `.bashrc`.
pub const BASH: &str = r##"# Bash completion for poe
# Generated by poethepoet, adapted by aeth-devkit: task data comes from `devkit complete`

_poe_complete() {
    local cur prev words cword
    _init_completion -n = 2>/dev/null || {
        COMPREPLY=()
        # Merge = signs split by COMP_WORDBREAKS (replicates -n = behavior)
        local _i _w _last_idx
        local -a _mw=()
        local _mc=0
        for (( _i=0; _i < ${#COMP_WORDS[@]}; _i++ )); do
            _w="${COMP_WORDS[_i]}"
            _last_idx=$(( ${#_mw[@]} - 1 ))
            if [[ "$_w" == "=" && ${#_mw[@]} -gt 0 ]]; then
                _mw[$_last_idx]+="="
                (( _i == COMP_CWORD )) && _mc=$_last_idx
            elif [[ ${#_mw[@]} -gt 0 && "${_mw[$_last_idx]}" == *= ]]; then
                _mw[$_last_idx]+="$_w"
                (( _i == COMP_CWORD )) && _mc=$_last_idx
            else
                (( _i == COMP_CWORD )) && _mc=${#_mw[@]}
                _mw+=("$_w")
            fi
        done
        words=("${_mw[@]}")
        cword=$_mc
        cur="${words[cword]}"
        if (( cword > 0 )); then prev="${words[cword-1]}"; else prev=""; fi
    }

    local target_path=""
    local task_position=""
    local potential_task=""
    local after_separator=""
    local i

    # Extract target_path from -C/--directory/--root and find task position
    for ((i=1; i < ${#words[@]}; i++)); do
        # Once we have a task, check for -- separator
        if [[ -n "$task_position" ]]; then
            if [[ "${words[i]}" == "--" ]]; then
                after_separator=1
            fi
            continue
        fi
        case "${words[i]}" in
            -C=*|--directory=*|--root=*)
                target_path="${words[i]#*=}"
                ;;
            -C|--directory|--root)
                if ((i+1 < ${#words[@]})); then
                    target_path="${words[i+1]}"
                    ((i++))
                fi
                ;;
            -*)
                # Skip options and their values (only if no = inline)
                if [[ "${words[i]}" != *=* ]]; then
                    case "${words[i]}" in
                        -h|--help|-C|--directory|-e|--executor|-X|--executor-opt)
                            ((i++))  # skip the value too
                            ;;
                    esac
                fi
                ;;
            *)
                # First non-option word is the task
                if [[ -z "$task_position" ]]; then
                    task_position=$i
                    potential_task="${words[i]}"
                fi
                ;;
        esac
    done

    # Complete global option values (early return) — only before the task
    if [[ -z "$task_position" ]] || ((cword <= task_position)); then
        # Handle --opt=value style for global options
        case "$cur" in
            -C=*|--directory=*|--root=*)
                local val="${cur#*=}" prefix="${cur%%=*}="
                _filedir 2>/dev/null || COMPREPLY=($(compgen -f -- "$val"))
                COMPREPLY=("${COMPREPLY[@]/#/$prefix}")
                return
                ;;
            -e=*|--executor=*)
                local val="${cur#*=}" prefix="${cur%%=*}="
                local -a vals
                vals=($(compgen -W "auto poetry simple uv virtualenv" -- "$val"))
                COMPREPLY=("${vals[@]/#/$prefix}")
                return
                ;;
        esac
        case "$prev" in
            -C|--directory|--root)
                _filedir 2>/dev/null || COMPREPLY=($(compgen -f -- "$cur"))
                return
                ;;
            -e|--executor)
                COMPREPLY=($(compgen -W "auto poetry simple uv virtualenv" -- "$cur"))
                return
                ;;
        esac
    fi

    # If cursor is at or before task position, complete tasks/global options
    if [[ -z "$task_position" ]] || ((cword <= task_position)); then
        if [[ "$cur" == -* ]]; then
            COMPREPLY=($(compgen -W "-h --help --version -v --verbose -q --quiet -d --dry-run -C --directory -e --executor -X --executor-opt --ansi --no-ansi" -- "$cur"))
        else
            # Only call _list_tasks when actually completing task names
            local tasks
            tasks=$(devkit complete tasks "$target_path" 2>/dev/null)
            COMPREPLY=($(compgen -W "$tasks" -- "$cur"))
        fi
        return
    fi

    # After --, only offer file completions (pass-through args to task)
    if [[ "$after_separator" == "1" ]] && ((cword > task_position)); then
        _filedir 2>/dev/null || COMPREPLY=($(compgen -f -- "$cur"))
        return
    fi

    # We're past the task position - complete task args
    local current_task="$potential_task"
    local show_task_opts=false

    # Get full task args info (tab-separated: opts, type, help, choices)
    local task_args_data
    task_args_data=$(devkit complete args "$current_task" "$target_path" 2>/dev/null)

    # Build list of option strings and track positional args
    local -a task_opts=()
    local -a positional_choices=()
    local -a boolean_opts=()
    while IFS=$'\t' read -r opts arg_type help_text choices; do
        [[ -z "$opts" ]] && continue
        [[ "$choices" == "_" ]] && choices=""
        if [[ "$arg_type" == "positional" ]]; then
            positional_choices+=("$choices")
        else
            # Split comma-separated options
            IFS=',' read -ra opt_arr <<< "$opts"
            task_opts+=("${opt_arr[@]}")
            if [[ "$arg_type" == "boolean" ]]; then
                boolean_opts+=("${opt_arr[@]}")
            fi
        fi
    done <<< "$task_args_data"

    # Count positional args already provided
    local positional_index=0
    for ((i=task_position+1; i < cword; i++)); do
        local word="${words[i]}"
        if [[ "$word" == -* ]]; then
            # Check if this is a known option (strip =value for matching)
            local opt_name="${word%%=*}"
            local is_opt=false is_bool=false
            for opt in "${task_opts[@]}"; do
                [[ "$opt_name" == "$opt" ]] && is_opt=true && break
            done
            if [[ "$is_opt" == true ]]; then
                for opt in "${boolean_opts[@]}"; do
                    [[ "$opt_name" == "$opt" ]] && is_bool=true && break
                done
                # Only skip next word if no = inline and not boolean
                [[ "$is_bool" == false && "$word" != *=* ]] && ((i++))
            fi
        else
            ((positional_index++))
        fi
    done

    # Handle --opt=value style for task options
    if [[ "$cur" == -*=* ]]; then
        local opt_part="${cur%%=*}" val_part="${cur#*=}"
        local opt_choices=""
        while IFS=$'\t' read -r opts arg_type help_text choices; do
            [[ -z "$opts" ]] && continue
            [[ "$choices" == "_" ]] && choices=""
            if [[ ",$opts," == *",$opt_part,"* ]]; then
                opt_choices="$choices"
                break
            fi
        done <<< "$task_args_data"
        local prefix="${opt_part}="
        if [[ -n "$opt_choices" ]]; then
            local -a vals
            vals=($(compgen -W "$opt_choices" -- "$val_part"))
            COMPREPLY=("${vals[@]/#/$prefix}")
        else
            _filedir 2>/dev/null || COMPREPLY=($(compgen -f -- "$val_part"))
            COMPREPLY=("${COMPREPLY[@]/#/$prefix}")
        fi
        return
    fi

    # If prev is an option, try to complete its value
    if [[ "$prev" == -* ]]; then
        # Find choices for this option
        local opt_choices=""
        local is_boolean=false
        while IFS=$'\t' read -r opts arg_type help_text choices; do
            [[ -z "$opts" ]] && continue
            [[ "$choices" == "_" ]] && choices=""
            if [[ ",$opts," == *",$prev,"* ]]; then
                if [[ "$arg_type" == "boolean" ]]; then
                    is_boolean=true
                else
                    opt_choices="$choices"
                fi
                break
            fi
        done <<< "$task_args_data"

        if [[ "$is_boolean" == true ]]; then
            show_task_opts=true
        elif [[ -n "$opt_choices" ]]; then
            COMPREPLY=($(compgen -W "$opt_choices" -- "$cur"))
            return
        elif [[ "$cur" == -* ]]; then
            show_task_opts=true
        else
            _filedir 2>/dev/null || COMPREPLY=($(compgen -f -- "$cur"))
            return
        fi
    fi

    # Show task options if cur starts with - OR we just handled a boolean flag
    if [[ "$cur" == -* ]] || [[ "$show_task_opts" == true ]]; then
        # Build set of all used option forms (including equivalents) in ONE pass
        # This avoids O(n²) re-parsing of task_args_data for each option
        local used_forms=" "
        for ((j=task_position+1; j < ${#words[@]}; j++)); do
            local word="${words[j]}"
            [[ "$word" != -* ]] && continue
            word="${word%%=*}"  # Strip =value for matching
            # Find this word's equivalence group and add ALL forms
            while IFS=$'\t' read -r opts arg_type help_text choices; do
                [[ -z "$opts" ]] && continue
                if [[ ",$opts," == *",$word,"* ]]; then
                    # Add all equivalent forms to used set
                    used_forms+="${opts//,/ } "
                    break
                fi
            done <<< "$task_args_data"
        done

        # Now filter: simple membership check
        local filtered_args=""
        for arg in "${task_opts[@]}"; do
            [[ "$used_forms" != *" $arg "* ]] && filtered_args+=" $arg"
        done

        if [[ -n "$filtered_args" ]]; then
            COMPREPLY=($(compgen -W "$filtered_args" -- "$cur"))
            return
        fi
    fi

    # Try positional argument choices
    if (( positional_index < ${#positional_choices[@]} )); then
        local pos_choices="${positional_choices[positional_index]}"
        if [[ -n "$pos_choices" ]]; then
            COMPREPLY=($(compgen -W "$pos_choices" -- "$cur"))
            return
        fi
    fi

    # Fall back to file completion
    _filedir 2>/dev/null || COMPREPLY=($(compgen -f -- "$cur"))
}

complete -F _poe_complete poe

"##;
